# Generates src\proxy\winmm_forwards.inc -- a PE export forwarder for every
# function the real winmm.dll exports that the proxy does not implement itself.
#
# WHY THIS IS NECESSARY
#
# A proxy DLL does not just serve the process it was planted for. It takes over
# the base name "winmm.dll" for the WHOLE process, and the loader binds every
# later module's winmm imports against it. SteamVR's vrclient_x64.dll imports
# timeSetEvent and timeKillEvent; when the proxy did not export those, the import
# bind failed, LoadLibrary(vrclient_x64.dll) was rejected, and OpenVR reported
# VRInitError_Init_VRClientDLLNotFound (102). A partial proxy is a latent bug for
# every DLL loaded after it, so the proxy exports all 180.
#
# The forwarders name winmm by ABSOLUTE PATH. A bare "winmm.NAME" forwarder would
# resolve by the normal search order, find the proxy itself, and recurse.
#
# Re-run this only if you need to regenerate for a different Windows build; the
# generated .inc is committed.

$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
$dest = Join-Path $root 'src\proxy\winmm_forwards.inc'

$dumpbin = Get-ChildItem "${env:ProgramFiles}\Microsoft Visual Studio\*\*\VC\Tools\MSVC\*\bin\Hostx64\x64\dumpbin.exe" -ErrorAction SilentlyContinue |
           Select-Object -First 1
if (-not $dumpbin) {
    $dumpbin = Get-ChildItem "${env:ProgramFiles(x86)}\Microsoft Visual Studio\*\*\VC\Tools\MSVC\*\bin\Hostx64\x64\dumpbin.exe" -ErrorAction SilentlyContinue |
               Select-Object -First 1
}
if (-not $dumpbin) { throw "dumpbin.exe not found; run from a VS developer prompt." }

$sysWinmm = Join-Path $env:SystemRoot 'System32\winmm.dll'
if (-not (Test-Path $sysWinmm)) { throw "not found: $sysWinmm" }

# Functions the proxy implements as real thunks (so its own init can run).
# These are exactly the ten tomb456.exe imports.
$thunked = @(
    'timeGetDevCaps','timeGetTime','timeBeginPeriod','timeEndPeriod',
    'waveOutOpen','waveOutClose','waveOutReset','waveOutWrite',
    'waveOutPrepareHeader','waveOutUnprepareHeader'
)

$exports = & $dumpbin.FullName /EXPORTS $sysWinmm |
    Select-String -Pattern '^\s+\d+\s+[0-9A-F]+\s+[0-9A-F]{8}\s+(\w+)' |
    ForEach-Object { $_.Matches[0].Groups[1].Value } |
    Sort-Object -Unique

if ($exports.Count -lt 100) { throw "only parsed $($exports.Count) exports; check dumpbin output format" }

# Escape backslashes for the C string literal inside the pragma.
$pathForC = (Join-Path $env:SystemRoot 'System32\winmm') -replace '\\', '\\'

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('// GENERATED by tools\gen_winmm_forwards.ps1 -- do not edit by hand.')
[void]$sb.AppendLine('//')
[void]$sb.AppendLine('// One PE export forwarder per real winmm export that the proxy does not')
[void]$sb.AppendLine('// implement itself. The target is spelled as an absolute path on purpose: a')
[void]$sb.AppendLine('// bare "winmm.NAME" would resolve by search order back to this DLL and recurse.')
[void]$sb.AppendLine('')

$count = 0
foreach ($e in $exports) {
    if ($thunked -contains $e) { continue }
    [void]$sb.AppendLine("#pragma comment(linker, `"/export:$e=$pathForC.$e`")")
    $count++
}

Set-Content -Path $dest -Value $sb.ToString() -Encoding utf8

Write-Host "wrote $dest"
Write-Host "  real winmm exports : $($exports.Count)"
Write-Host "  thunked by proxy   : $($thunked.Count)"
Write-Host "  forwarded          : $count"
